config/routes.rb
Rails.application.routes.draw do
  resources :meetings do 
    resources :meetingcomments
  end
  resources :profiles, except: [:edit]
  patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#index', as: 'root'
  resources :mailform
  resources :blogs
  get 'CV', to: 'pages#CV', as: :cv
  get 'adminpanel', to: 'pages#adminpanel', as: :adminpanel
  get 'lol', to: 'pages#lol', as: :lol
  get 'longermsg', to: 'pages#longermsg', as: :longermsg
  get 'daily', to: 'pages#daily', as: :daily
  get 'weekly', to: 'pages#weekly', as: :weekly
  get 'meetingfilter', to: 'pages#meetingfilter', as: :meetingfilter
  resources :coachingrequests
  get 'aboutus', to: 'pages#aboutus', as: :aboutus
  get 'networking', to: 'pages#networking', as: :networking
  get 'request submission', to: 'pages#requestsubmission', as: :requestsubmission
  resources :ukfinancejobs, except: [:edit] do 
    resources :comments
    member do
      post 'favorite', to: 'ukfinancejobs#favorite'
      delete 'unfavorite', to: 'ukfinancejobs#unfavorite'
    end
    collection do
      get 'favorites', to: 'ukfinancejobs#favorites'
    end
  end
  patch '/ukfinancejobs/:id', to: 'ukfinancejobs#update', as: 'update_ukfinancejob'
  get '/ukfinancejobs/:id/edit', to: 'ukfinancejobs#edit', as: 'edit_ukfinancejob'
  get 'interviews', to: 'pages#interviews', as: :interview
  get '/downloads/:filename', to: 'downloads#download', as: 'download_file'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_one_attached :photo
end

app/models/coachingrequest.rb
class Coachingrequest < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ukfinancejob
  belongs_to :user
  
  validates :content, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :ukfinancejob
end

app/models/mailform.rb
class Mailform < ApplicationRecord
	  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	has_one_attached :photo1
	has_many :meetingcomments
	validates :name, :start_time, :photo1, :location, :virtual_or_inperson,:description, :link_to_url, :eligibility, :company, :industry, :deadline_date, presence: true


end

app/models/meetingcomment.rb
class Meetingcomment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
end

app/models/ukfinancejob.rb
class Ukfinancejob < ApplicationRecord
	require 'pg_search'
	has_one_attached :photo
	has_many :comments, dependent: :destroy
	validates :title, :url, :company, :type_of_job, :location, :application_opening_date, :deadline_date, :eligibility, :industry, :hr_email, :app_process, :description, presence: true
 	has_many :favorites
  has_many :favorited_by_users, through: :favorites, source: :user

  include PgSearch::Model
	pg_search_scope :search_by_keyword, against: %i[title company type_of_job location description],
                                    using: {
                                      tsearch: { prefix: true }
                                    }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  after_create :create_profile

  private

  def create_profile
    build_profile.save
  end

  has_many :favorites
  has_many :favorite_ukfinancejobs, through: :favorites, source: :ukfinancejob

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
	end
	
	def show
		@blog = Blog.find(params[:id])
	end
	
	def create
		@blog = Blog.new(blog_params)
		if @blog.save
		    redirect_to root_path
		else
		    render :new
		end
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		if @blog.update(blog_params)
	      redirect_to @blog
	    else
	      render :edit
	    end
	end

	private

	def blog_params
		params.require(:blog).permit(:photo, :title, :para1, :para2, :para3, :para4, :para5, :desc)
	end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.order(:start_time)
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to networking_path, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :photo1, :location, :virtual_or_inperson,:description, :link_to_url, :eligibility, :company, :industry, :deadline_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/mailform_helper.rb
module MailformHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/userprofile_helper.rb
module UserprofileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html.erb
<section class="container">
  

<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company, class: 'form-control' %>
  </div>
  <br>

  <div>
    <%= form.label :industry, style: "display: block" %>
    <%= form.select :industry, options_for_select(['Sell side', 'Buy side']), {}, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :eligibility, style: "display: block" %>
    <%= form.text_field :eligibility, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :virtual_or_inperson, style: "display: block" %>
    <%= form.text_field :virtual_or_inperson, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :link_to_url, style: "display: block" %>
    <%= form.text_field :link_to_url, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :deadline_date, style: "display: block" %>
    <%= form.datetime_field :deadline_date, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
      <%= form.file_field :photo1, as: :file %>
  </div>
  <br>
  <div>
    <%= form.submit "create", class: "btn btn-white d-flex" %>
  </div>
<% end %>
</section>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <h4 class="text-center">
    <%= meeting.name %>
  </h4>

  <p class="text-center">
    <%= meeting.start_time.day %>
    
    <%= t('date.month_names')[meeting.start_time.month] %> <%= meeting.start_time.year %>

    - 
 
    <%= meeting.start_time.strftime("%H:%M") %> (UK time)

    <br>
    <strong>
      <%= meeting.virtual_or_inperson %>   meeting
    </strong> 
  </p>

<section class="mobile-only">
  
  <div class="d-flex justify-content-center">
      <%= cl_image_tag meeting.photo1.key, height: 100, crop: :fill %>
  </div>

  <br>

  <div>
    <p>
      <strong style="padding-right: 5px;">description: </strong>
    </p>
    <p style="margin-top:-15px;">
      <%= meeting.description %>  
    </p>
  </div>
<br>
  <div class="d-flex justify-content-center">
    <strong>  
      <a href="<%= meeting.link_to_url %>" style="color: white;" class="no-style btn-dark p-3 round-border" target="_blank">  
        Link to event
      </a>
    </strong>
  </div>
    
</section>

<!-- desktop only -->

<section class="desktop-only" >
  
  <div class="d-flex justify-content-center">
      <%= cl_image_tag meeting.photo1.key, height: 100, crop: :fill %>
  </div>

  <br>

    <div>
    <p  class="text-center">
      <strong style="padding-right: 5px;">description: </strong>
    </p>
    <p style="margin-top:-15px;"  class="text-center">
      <%= meeting.description %>  
    </p>
  </div>
<br>
  
  <div class="d-flex justify-content-center">
    <strong>  
      <a href="<%= meeting.link_to_url %>" style="color: white;" class="no-style btn-dark p-3 round-border" target="_blank">  
        Link to event
      </a>
    </strong>
  </div>
    
</section>

</div>
<br>

<hr>

<!-- job comments -->

<div class="container">
  
<h4 class="text-center">Comments</h4>
<br>

<% @meeting.meetingcomments.each do |comment| %>
  <div class=" m-3 p-2 round-border">
    <p>
      <%= comment.content %>  
    </p>
    <p>
      <i class="fa-sharp fa-regular fa-user"></i> <%= link_to comment.user.email.split("@").first, profile_path(comment.user), class: "no-style" %>
      <span style="font-size:12px;">
        on <%= comment.created_at.strftime("%e %B %Y") %>  
      </span>
    </p>
  </div>
  <hr>
<% end %>

<% if current_user.present? %>
    <%= form_with(model: [@meeting, Meetingcomment.new], url: meeting_meetingcomments_path(@meeting)) do |form| %>
    <div> 
      <%= form.text_area :content, placeholder: 'Enter your comment', class: "d-flex w-100" %>
    </div>
    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
    <br>
    <%= form.submit 'Add Comment', class: "btn btn-green w-100" %>
  <% end %>
<% else %>
<p>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-green' %>
  to comment
</p>
<% end %>

</div>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meetings</h1>

<div id="meetings">
  <% @meetings.each do |meeting| %>
    <%= render meeting %>
    <p>
      <%= link_to "Show this meeting", meeting %>
    </p>
  <% end %>
</div>

<%= link_to "New meeting", new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Back to calendar", networking_path, class: "btn btn-green" %>
</div>
<br>
<%= render @meeting %>


<br>
<div>
<% if current_user and current_user.admin == true %>
  <%= link_to "Edit this meeting", edit_meeting_path(@meeting), class: "btn" %> 
  
  <%= button_to "Destroy this meeting", @meeting, method: :delete, class: "btn " %>
<% end %>
</div>