config/routes.rb
Rails.application.routes.draw do
  resources :meetings do 
    resources :meetingcomments
  end
  resources :profiles, except: [:edit]
  patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#index', as: 'root'
  resources :mailform
  resources :blogs
  get 'CV', to: 'pages#CV', as: :cv
  get 'adminpanel', to: 'pages#adminpanel', as: :adminpanel
  get 'lol', to: 'pages#lol', as: :lol
  get 'longermsg', to: 'pages#longermsg', as: :longermsg
  get 'daily', to: 'pages#daily', as: :daily
  get 'weekly', to: 'pages#weekly', as: :weekly
  get 'meetingfilter', to: 'pages#meetingfilter', as: :meetingfilter
  resources :coachingrequests
  get 'aboutus', to: 'pages#aboutus', as: :aboutus
  get 'networking', to: 'pages#networking', as: :networking
  get 'request submission', to: 'pages#requestsubmission', as: :requestsubmission
  resources :ukfinancejobs, except: [:edit] do 
    resources :comments
    member do
      post 'favorite', to: 'ukfinancejobs#favorite'
      delete 'unfavorite', to: 'ukfinancejobs#unfavorite'
    end
    collection do
      get 'favorites', to: 'ukfinancejobs#favorites'
    end
  end
  patch '/ukfinancejobs/:id', to: 'ukfinancejobs#update', as: 'update_ukfinancejob'
  get '/ukfinancejobs/:id/edit', to: 'ukfinancejobs#edit', as: 'edit_ukfinancejob'
  get 'interviews', to: 'pages#interviews', as: :interview
  get '/downloads/:filename', to: 'downloads#download', as: 'download_file'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_one_attached :photo
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
	end
	
	def show
		@blog = Blog.find(params[:id])
	end
	
	def create
		@blog = Blog.new(blog_params)
		if @blog.save
		    redirect_to root_path
		else
		    render :new
		end
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		if @blog.update(blog_params)
	      redirect_to @blog
	    else
	      render :edit
	    end
	end

	private

	def blog_params
		params.require(:blog).permit(:photo, :title, :para1, :para2, :para3, :para4, :para5, :desc)
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<br>
<h3 class="text-center">Edit blog</h3>
<%= form_with(model: @blog, url: blogs_path) do |form| %>
  
<div class="form-group d-flex justify-content-center">
<%= form.text_field :title, placeholder: 'title',  class: 'form-control short-input'  %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :desc, class: 'TXT-area', placeholder: 'desc' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para1, class: 'TXT-area', placeholder: 'Para1' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para2, class: 'TXT-area', placeholder: 'Para2' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para3, class: 'TXT-area', placeholder: 'Para3' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para4, class: 'TXT-area', placeholder: 'Para4' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para5, class: 'TXT-area', placeholder: 'Para5' %>
  </div>
  <br>
  <div class="actions d-flex justify-content-center">
    <%= form.submit 'SUBMIT', class: 'btn btn-primary btn-dark' %>
  </div>
<% end %>

<style type="text/css">
	.short-input{
		width: 400px;
		height: 50px;
	}
	.long-input{
		width:  400px;
		height: 150px;
	}

	.TXT-area{
		width: 400px;
	}
</style>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>How to get a job in finance - Blogposts</title>
</head>
<body>
<br>
<h2 class="text-center">
  How to get a job in finance - Blogposts
</h2>
<h6 class="text-center">
	Weekly blogposts - with specific & value-adding details.
</h6>

<% if current_user and current_user.admin == true %>
  <%= link_to 'Add a Blog', new_blog_path, class: 'btn btn-primary btn-dark' %>
<% end %>





<div class="ukfinancejob-container">
  <% @blogs.each do |blogpost| %>
    <div class="ukfinancejob-card">
      <div class="card">
        <div class="card-body">
          <div style="display: block; position: absolute; right:10px; top: 10px;">
            <%= cl_image_tag blogpost.photo.key, height: 80, width: 106, crop: :fill %>
          </div>
          <h5 class="card-title"><%= blogpost.title %></h5>
          <br>
          <br>
          <p class="card-text"><strong>Description:</strong> <%= blogpost.para1 %></p>
          <br>
          <%= link_to 'View', blog_path(blogpost), class: 'btn btn-white', style: 'width: 100%' %>
          <br>
          <br>
          
          <div class="d-flex justify-content-around">	

          <% if current_user and current_user.admin == true %>
			       <%= link_to 'Edit', edit_blog_path(blogpost), class: 'btn btn-primary' %>

			       <%= button_to 'Delete', blog_path(blogpost), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this job?' }, form: { "data-remote": true } %>
          <% end %>
          </div>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/blogs/new.html.erb
<br>
<h3 class="text-center">Add a blog</h3>
<%= form_with(model: @blog, url: blogs_path) do |form| %>
  
<div class="form-group d-flex justify-content-center">
<%= form.text_field :title, placeholder: 'title',  class: 'form-control short-input'  %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :desc, class: 'TXT-area', placeholder: 'desc' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para1, class: 'TXT-area', placeholder: 'Para1' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para2, class: 'TXT-area', placeholder: 'Para2' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para3, class: 'TXT-area', placeholder: 'Para3' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para4, class: 'TXT-area', placeholder: 'Para4' %>
  </div>
  <br>
  <div class="form-group d-flex justify-content-center">
    <%= form.text_area :para5, class: 'TXT-area', placeholder: 'Para5' %>
  </div>
  <br>
  <div class="form-group">
      <%= form.file_field :photo, as: :file %>
  </div>
  <br>
  <div class="actions d-flex justify-content-center">
    <%= form.submit 'SUBMIT', class: 'btn btn-primary btn-dark' %>
  </div>
<% end %>

<style type="text/css">
	.short-input{
		width: 400px;
		height: 50px;
	}
	.long-input{
		width:  400px;
		height: 150px;
	}

	.TXT-area{
		width: 400px;
	}
</style>

app/views/blogs/show.html.erb
<!-- app/views/ukfinancejobs/show.html.erb -->
  <div class="container">
    <%= link_to 'Back to all blogs', blogs_path, class: 'btn btn-white' %>
    <h1 class="text-center"><%= @blog.title %></h1>
    <div class="d-flex justify-content-center">
      <%= cl_image_tag @blog.photo.key, height: 300, width: 400, crop: :fill %>
    </div>  
    <div class="ukfinancejob-details">
      <br>
      <p class="text-center"><strong>Description:</strong> <%= @blog.desc %></p>
      <p class="text-center"><%= @blog.para1 %></p>
      <p class="text-center"><%= @blog.para2 %></p>
      <p class="text-center"><%= @blog.para3 %></p>
      <p class="text-center"><%= @blog.para4 %></p>
      <p class="text-center"><%= @blog.para5 %></p>
    </div>  
  </div>
</div>


<% if current_user and current_user.admin == true %>

<div class="d-flex justify-content-around"> 
<%= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-primary' %>

<%= button_to 'Delete', blog_path(@blog), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this job?' }, form: { "data-remote": true } %>

    </div>
<% end %>