config/routes.rb
Rails.application.routes.draw do
  resources :meetings do 
    resources :meetingcomments
  end
  resources :profiles, except: [:edit]
  patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#index', as: 'root'
  resources :mailform
  resources :blogs
  get 'CV', to: 'pages#CV', as: :cv
  get 'adminpanel', to: 'pages#adminpanel', as: :adminpanel
  get 'lol', to: 'pages#lol', as: :lol
  get 'longermsg', to: 'pages#longermsg', as: :longermsg
  get 'daily', to: 'pages#daily', as: :daily
  get 'weekly', to: 'pages#weekly', as: :weekly
  get 'meetingfilter', to: 'pages#meetingfilter', as: :meetingfilter
  resources :coachingrequests
  get 'aboutus', to: 'pages#aboutus', as: :aboutus
  get 'networking', to: 'pages#networking', as: :networking
  get 'request submission', to: 'pages#requestsubmission', as: :requestsubmission
  resources :ukfinancejobs, except: [:edit] do 
    resources :comments
    member do
      post 'favorite', to: 'ukfinancejobs#favorite'
      delete 'unfavorite', to: 'ukfinancejobs#unfavorite'
    end
    collection do
      get 'favorites', to: 'ukfinancejobs#favorites'
    end
  end
  patch '/ukfinancejobs/:id', to: 'ukfinancejobs#update', as: 'update_ukfinancejob'
  get '/ukfinancejobs/:id/edit', to: 'ukfinancejobs#edit', as: 'edit_ukfinancejob'
  get 'interviews', to: 'pages#interviews', as: :interview
  get '/downloads/:filename', to: 'downloads#download', as: 'download_file'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_one_attached :photo
end

app/models/coachingrequest.rb
class Coachingrequest < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ukfinancejob
  belongs_to :user
  
  validates :content, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :ukfinancejob
end

app/models/mailform.rb
class Mailform < ApplicationRecord
	  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	has_one_attached :photo1
	has_many :meetingcomments
	validates :name, :start_time, :photo1, :location, :virtual_or_inperson,:description, :link_to_url, :eligibility, :company, :industry, :deadline_date, presence: true


end

app/models/meetingcomment.rb
class Meetingcomment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
end

app/models/ukfinancejob.rb
class Ukfinancejob < ApplicationRecord
	require 'pg_search'
	has_one_attached :photo
	has_many :comments, dependent: :destroy
	validates :title, :url, :company, :type_of_job, :location, :application_opening_date, :deadline_date, :eligibility, :industry, :hr_email, :app_process, :description, presence: true
 	has_many :favorites
  has_many :favorited_by_users, through: :favorites, source: :user

  include PgSearch::Model
	pg_search_scope :search_by_keyword, against: %i[title company type_of_job location description],
                                    using: {
                                      tsearch: { prefix: true }
                                    }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  after_create :create_profile

  private

  def create_profile
    build_profile.save
  end

  has_many :favorites
  has_many :favorite_ukfinancejobs, through: :favorites, source: :ukfinancejob

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/mailform_helper.rb
module MailformHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ai/_output.html.erb
<div class="card">
	<% if generated_idea %>
		<%= content_tag(:div, generated_idea) %>
	<% end %>
</div>

app/views/ai/_request_form.html.erb
<%= form_for :ai_request, url: ai_request_path, method: :post, remote: :true do |f| %>
	<%= f.hidden_field :uuid, value: @uuid %>
		<div class="form-group">
			<%= f.text_area :prompt, class: "form-control" %>
		</div>

	<%= f.select :ai_model, options_for_select([
		[ "Ada $0.0016 / 1k tokens", "ada"],
		[ "Babbage $0.0024 / 1k tokens", "babbage"],
		[ "Curie $0.0120 / 1k tokens", "curie"], 
		[ "Davinci $0.1200 / 1k tokens", "davinci"]
	], "davinci"), {}, class: "form-control" %>
	<%= f.submit "send" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Graduate Flow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_importmap_tags %>
  </head>

  <script async src="https://www.googletagmanager.com/gtag/js?id=G-8N2W6MJ28G"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-8N2W6MJ28G');
  </script>

  <%= favicon_link_tag 'favicon.ico' %>


  <body>
    <% if current_user and current_user.admin == true %>
      <%= render :partial => 'pages/header' %>
      <%= yield %>
      <%= render :partial => 'pages/footer' %>
    <% else %>
      <p>Offline/Under Maintenance</p>
    <% end %>

  </body>
</html>

app/views/pages/_header.html.erb
<style type="text/css">
  /* Adjust the header styles according to your design requirements */
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: -40px;
  margin-bottom: -60px;
}

/* Style the burger icon */
.burger-icon {
  display: inline-block;
  width: 30px;
  height: 3px;
  background-color: #000; /* Change this to the color of your burger icon */
  position: relative;
}

/* Add any other styles you need for the logo container */
.logo-container {
  /* Add any additional styles for positioning and sizing the logo */
}

/* Add any other styles you need for the logo image */
.logo-container img {
    width: 150px; /* Set the width of the logo image to 50px */
    margin-left: -25px;
    margin-top:-25px;
}
.margin-right-btn{
  margin-right:30px;
  margin-bottom:25px;
}

.desktop-logo{
  width:100px;
  margin-right: -15px;
}
</style>

<div class="header">
  <div class="logo-container mobile-only">
        <%= link_to root_path, class: "no-style" do %>
      <img src="<%= asset_path('logo.png') %>" alt="Logo" class="desktop-logo">
    <% end %>
  </div>
  
  <button class="btn-non-bounce margin-right-btn mobile-only btn-dark" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" id="toggleDropdown">
    <span class="burger-icon"></span>
  </button>
</div>

  <div class="collapse mobile-only" id="collapseExample" style="background-color: rgba(239, 239, 240); margin-top:10px;">       
            <table  class="table table-hover table-condensed  " >
            <thead>
              <tr>
                <th style="width:50% "></th>
              </tr>
            </thead>
            <tbody>
              <br>
              <tr>
                <span style="margin-left:10px; margin-right:-15px;">
                    <i class="fa-solid fa-magnifying-glass"></i>
                  </span>
                  <%= link_to "Job Filter", ukfinancejobs_path, class: "btn header-link"  %>
                  
              </tr>
              <hr>
              <tr>
                <span style="margin-left:10px; margin-right:-15px;">
                    <i class="fa-regular fa-calendar"></i>
                  </span>
                <%= link_to "Networking & Events Calendar", networking_path, class: "btn header-link" %>
                
              </tr>
              <hr>
              <tr>
                <span style="margin-left:10px; margin-right:-15px;">
                  <i class="fa-regular fa-file-word"></i>
                </span>
                <%= link_to "CV & Cover Letters", cv_path, class: "btn header-link" %>  
                
              </tr>

              <hr>
              <tr>
                <span style="margin-left:10px; margin-right:-15px;">
                  <i class="fa-solid fa-table-columns"></i>
                </span>
                
                <%= link_to "Daily Update", daily_path, class: "btn header-link "  %>               
              </tr>

              <hr>
              

              <br>
              <tr>
                <% if user_signed_in? %>
                    <div style="margin-left:10px;"> 
                        <%= link_to profile_path(current_user.id), class: "btn-dark btn border-light header-link-desktop" do %>
                        <span class="p-2">
                          <i class="fa-solid fa-user"></i> Profile  
                        </span>
                        
                        <% end %>
                    </div>
                <% else %>
                <div style="margin-left:10px;"> 
                      <%= link_to "Login", new_user_session_path, class: "btn-dark btn border-light" %>
                </div>
                <br>
                <div style="margin-left:10px;"> 
                  <%= link_to "Register", new_user_registration_path, class: "btn btn-green border-light"  %>
                </div>
                    
                <% end %>
              </tr>
            </tbody>
          </table>
          </div>


<span class="desktop-only">

</span>
<section class="fae-this .collapse.show.bouncy-element"> 
  <h1 class="text-center no-style mt-3 background">
    <%= link_to root_path, class: "no-style" do %>
      <img src="<%= asset_path('logo.png') %>" alt="Logo" class="desktop-only desktop-logo">
    <% end %>
    <%= link_to "Graduate Flow", root_path, class: "no-style" %>

  </h1>
<div class="sub-header background">
<h6 style="font-size:15px;">How to really find a job within finance (UK & Europe)</h6>
</div>
<nav class="desktop-only">
<ul>
  <li>
    <%= link_to "CV & Cover Letters", cv_path, class: "header-link-desktop" %>  
  </li>
  <li>
    <%= link_to "Networking Calendar", networking_path, class: "header-link-desktop"  %>  
  </li>
  <li>
    <%= link_to "Job Finder", ukfinancejobs_path, class: "header-link-desktop"  %>
  </li>
  <li>
    <%= link_to "Daily Update", daily_path, class: "header-link-desktop"  %>
  </li>
  
  <% if user_signed_in? %>
    <% if Profile.find_by(user_id: current_user.id).present? %>
    <li>
      <div style="margin-left:10px;"> 
        <%= link_to profile_path(current_user.id), class: "btn-dark btn border-light header-link-desktop" do %>
                        <span class="p-2">
                          <i class="fa-solid fa-user"></i> Profile  
                        </span>
                    <% end %>
      </div>
    </li>
    <% end %>
<% else %>
<li>
  <div>
  <%= link_to "Login", new_user_session_path, class: "btn-dark btn border-light" %>
  </div>
  
</li>
<% end %>
</ul>

</nav>
</section>






<style type="text/css"> 
/* Add these styles to create the burger icon */
.burger-icon {
  display: inline-block;
  width: 25px;
  height: 3px;
  background-color: #fff;
  margin: 5px 0;
  transition: transform 0.3s;
}

/* Add this style to rotate the top and bottom lines of the burger icon on click */
.btn.btn-green[aria-expanded="true"] .burger-icon {
  transform: rotate(45deg);
}

/* Add this style to hide the middle line of the burger icon on click */
.btn.btn-green[aria-expanded="true"] .burger-icon::before {
  content: '';
  display: block;
  width: 25px;
  height: 3px;
  background-color: #fff;
  position: absolute;
  top: 0;
  transform: rotate(-90deg);
}

/* Add these styles to create the burger icon */
.burger-icon {
  display: inline-block;
  width: 25px;
  height: 3px;
  background-color: #fff;
  margin: 5px 0;
  transition: transform 0.3s;
}

/* Add this style to rotate the lines of the burger icon on click */
.btn.btn-green[aria-expanded="true"] .line:nth-child(1) {
  transform: rotate(45deg) translate(5px, 5px);
}

.btn.btn-green[aria-expanded="true"] .line:nth-child(2) {
  opacity: 0;
}

.btn.btn-green[aria-expanded="true"] .line:nth-child(3) {
  transform: rotate(-45deg) translate(5px, -5px);
}

.btn-non-bounce{
    padding: 10px 20px;
  border: none;
  border-radius: 5px;
  font-size: 16px;
  cursor: pointer;
  transition: transform 0.3s;
}

.header-link{
  font-size:17px;

}


.collapse{
width: 100%;
}

.header-link{
  font-size:16px;
}

.blur-effect {
  filter: blur(5px);
}

.header-link-desktop:hover{
  background-color: rgba(35,180,205,255);
}
</style>
<hr>


<div class="background" id="background">

<script type="text/javascript">
// JavaScript
function toggleBlurEffect() {
  var contentToBlur = document.querySelectorAll(".background");
  var isBlurEnabled = false;

  function applyBlur() {
    contentToBlur.forEach(function(element) {
      if (isBlurEnabled) {
        element.classList.add("blur-effect");
      } else {
        element.classList.remove("blur-effect");
      }
    });
  }

  var burgerButton = document.querySelector(".btn-non-bounce.mobile-only");
  burgerButton.addEventListener("click", function() {
    isBlurEnabled = !isBlurEnabled;
    applyBlur();
  });

  // Apply the blur effect initially
  applyBlur();

  // Apply the blur effect again whenever the content is loaded via AJAX
  document.addEventListener("DOMContentLoaded", function() {
    applyBlur();
  });
}
toggleBlurEffect();
</script>


<% if current_user and current_user.admin == true %>
<div class="d-flex justify-content-center">
    <%= link_to 'daily msg', lol_path, class: 'btn btn-primary btn-dark m-2' %>
    <%= link_to '3-day update msg', longermsg_path, class: 'btn btn-primary btn-dark m-2' %>
    <%= link_to 'stats', adminpanel_path, class: 'btn btn-primary btn-dark m-2' %>    
</div>
<% end %>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% content_for :title, 'Graduate Flow  - Find a Job in Finance and Consulting' %>
  <% content_for :description, 'Discover how to really find a job within finance and consulting. Dorsia Recruiting offers CV tips, interview guidance, networking strategies, and more.' %>
  <title>Graduate Flow</title>
</head>





<br>
<section class="page-section fade-this" id="animated-div" style="margin-top:-100px;">
    <div class="container">
        <ul class="timeline">
            <li>
                <div class="timeline-image">
                    <p class="desktop-only" style="font-size:50px; margin-top:25%">
                        1
                    </p>
                    <p class="mobile-only" style="margin-top:19px;">
                        1
                    </p>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        
                        <%= link_to ukfinancejobs_path, class: 'btn btn-green w-100' do %>
                            <span>
                                <i class="fa-solid fa-magnifying-glass"></i>
                                Job Filter
                            </span>
                            
                        <% end %>
                    </div>
                    <div class="timeline-body">
                        <p class="p-smaller p-1 text-center">Find all <strong>relevant</strong> internships in finance. </p>
                    </div>
                </div>
            </li>
            
            <li class="timeline-inverted">
                <div class="timeline-image">
                    <p class="desktop-only" style="font-size:50px; margin-top:25%">
                        2
                    </p>
                <p class="mobile-only" style="margin-top:19px;">
                    2
                </p>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                    <%= link_to networking_path, class: 'btn btn-green w-100' do %>
                    <span>
                        <i class="fa-regular fa-calendar"></i>
                            Calendar
                    </span>
                    <% end %> 
                    </div>
                    <div class="timeline-body p-smaller p-1 text-center">
                        A calendar to find all virtual/in person finance-related networking events in Europe & London.
                    </div>

                        
                </div>
                
            </li>
            <li>
                <div class="timeline-image">
                    <p class="desktop-only" style="font-size:50px; margin-top:25%">
                        3
                    </p>
                    <p class="mobile-only" style="margin-top:19px;">
                        3
                    </p>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="subheading">
                            <%= link_to cv_path, class: 'btn-green btn w-100' do %>
                            <span>
                              <i class="fa-regular fa-file-word"></i>
                                CV & Cover Letters
                            </span>
                            <% end %>
                        </h4>                      
                    </div>
                    <div class="timeline-body">
                        <p class="p-smaller text-center">Use our built-in Chat-GPT processor to create your first CV and cover letter.</p>
                    </div>
                </div>
            </li>
            
            <li class="timeline-inverted">
              <div class="timeline-image">
                <p class="desktop-only" style="font-size:50px; margin-top:25%">
                        4
                    </p>
                <p class="mobile-only" style="margin-top:19px;">
                        4
                    </p>
              </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="subheading">Reminders!</h4>
                    </div>
                    <p class="p-smaller">
                        stay up to date:
                    </p>

                    <%= link_to new_mailform_path, class: 'mt-3 btn btn-green w-100' do %>
                    <span>  
                        <i class="fa-regular fa-envelope"></i> Email List
                    </span>
                    
                    <% end %>
                    <div class="mt-3">
                        <%= link_to 'https://chat.whatsapp.com/LfCmhGNOvw86hkVJ5JGUrK', class: 'btn btn-green w-100 msg-link', style: "max-height:40px;", target: "_blank" do %>   

                        <p> <i class="fa-brands fa-whatsapp"> </i> Whatsapp Group </p>   
                        <% end %> 
                    </div>
                    <div class="mt-3">
                        <%= link_to 'https://t.me/+q0_Cgf4wFlk2MTI0', class: 'btn btn-green w-100 msg-link',style: "max-height:40px;", target: "_blank"  do %>   
                        <p><i class="fa-brands fa-telegram"></i> Telegram Group </p>   
                        <% end %> 
                    </div>

                    <p class="p-smaller p-1"><strong>Only the admin writes </strong> (to avoid spam) </p>
                </div>
            </li>
           
        </ul>
    </div>
</section>


<style type="text/css">
  @media (max-width: 900px) {
    .desktop-only{
      display:none;
      }
}
.p-smaller{
    font-size:15px;
}


</style>

app/views/pages/networking.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Networking Calendar - UK and Europe finance jobs</title>
</head>
<body>

<% if current_user and current_user.admin == true %>
  <%= link_to "new event", new_meeting_path, class: "btn btn-white" %>
<% end %>

<br>
<br>
<h4 class="text-center">
  <i class="fa-regular fa-calendar"></i> Networking Calendar 
</h4>

<h5 class="text-center heartbeat-text" style="">
  <%= Meeting.all.count %> events posted
</h5>
<br>

<button class="btn mobile-only w-100 btn-green" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample1">+ What is this?</button>

<div class="d-flex justify-content-center">
  <button class="btn desktop-only btn-green" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample1">+ What is this?</button>  
</div>


<br>
         
<div class="collapse -only" id="collapseExample1">
  <p class="container">
    This calendar will inform you about any virtual/in person networking or firmwide events available within London/Europe. Click on an event for more details on registrations.
  </p>
  <p class="container" style="margin-top:-20px;">
    Attending these networking sessions - especially if they are in person - can be <strong>vital to your success in finding a job.</strong>
    <hr>
  </p>

</div>


<!--
<div class="d-flex justify-content-center desktop-only">
  <%= link_to "Filter Events", meetingfilter_path,  class: " desktop-only btn btn-dark" %>  
</div>
-->

<div class="desktop-only">
<%= month_calendar(events: @meetings) do |date, meetings| %>
  <%= date.day %>
  <% meetings.each do |meeting| %>
    <%= link_to meeting_path(meeting) do %>

    <i class="fa-regular fa-circle-dot" style="color: red;">
     </i>
     <br>


     <div class="d-flex justify-content-center mt-3" style="background-image: url('<%= cl_image_path meeting.photo1.key %>'); width: 100%; height: 80px; max-height: 80px; background-size: contain; background-repeat: no-repeat; background-position: center;"></div>
     
     <% end %>

    <br>
    <div class="d-flex justify-content-center">
      
      <p style="margin-left:10px; margin-top: -18px;">
        <%= meeting.virtual_or_inperson %>
      </p>
    </div>
    <div class="d-flex justify-content-center italic_small" style="margin-top:-12px; font-size: 14px;">  
      <p class="text-center">
        <%= meeting.location %>
      </p>
    </div>

  <% end %>
<% end %> 
</div>
<!--
<div class="mobile-only mt-4">
  <p class="text-center">
  <strong>
    click on company names for details!
  </strong>
</p>
  <%= month_calendar(events: @meetings) do |date, meetings| %>
  <%= date.day %>

  <% meetings.each do |meeting| %>
  <% if meeting.present? %>
    <%= link_to meeting_path(meeting) do %>
    <i class="fa-regular fa-circle-dot" style="color: red;">
     </i>
     <br>
     <br>

     <div class="d-flex justify-content-center mt-3" style="background-image: url('<%= cl_image_path meeting.photo1.key %>'); width: 100%; height: 80px; max-height: 80px; background-size: contain; background-repeat: no-repeat; background-position: center;"></div>

     <% end %>
     
    </div>
  <% end %>
  <br>
    <div class="d-flex">
      
      <p style="margin-top:-30px; width:100%; color: blue;">
        <%= meeting.company %>
      </p>
    </div>
    <div class="d-flex italic_small" style="margin-top:-12px; font-size: 14px;">  
      <p class="text-center">
        <%= meeting.virtual_or_inperson %>
      </p>
    </div>

  <% end %>
<% end %>
</div>
--> 



<div class="filter-container mobile-only">
  <div class="filter-container">
  <form action="<%= meetingfilter_path %>" method="get">
    <div class="form-row">
      <div class="col-md-3 p-3">
        <%= select_tag :company, options_for_select([["Company", ""]].concat(@companies), params[:company]), { class: "form-control" } %>
      </div>
      <div class="col-md-3 p-3">
        <%= select_tag :industry, options_for_select([["Industry", ""]].concat(@industries), params[:industry]), { class: "form-control" } %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-md-3 p-3">
        <%= select_tag :location, options_for_select([["Location", ""]].concat(@locations), params[:location]), { class: "form-control" } %>
      </div>
      <div class="col-md-3 p-3">
        <%= select_tag :virtual_or_inperson, options_for_select([["Job type", ""]].concat(@virtual_or_inperson_options), params[:virtual_or_inperson]), { class: "form-control" } %>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= submit_tag "Filter", class: "btn btn-dark", style: "width: 30%;" %>
    </div>
    <div class="d-flex mt-3 justify-content-center">
      <%= link_to "Reset ", meetingfilter_path, class: "btn btn-green", style: "width: 30%;"  %>
    </div>
  </form>
</div>
</div>
<div class="mobile-only">
<div class="card-container" id="cardContainer" style="width: 100%; display: flex; flex-wrap: wrap; justify-content: center;">
  <% @meetings.each do |meeting| %>
  <% if meeting.present? %>
    <div class="card" style="background-color: white; border: 1px solid black; padding: 5px; width: 155px; height: 300px; margin: 5px; display: flex; flex-direction: column; justify-content: space-between;">
      <div style="flex: 1;">
        <h6 class="text-center bold" style="max-height: 2.5em; height: 2.5em; overflow: hidden;"><%= meeting.name %></h6>
        <div class="d-flex justify-content-center mt-3" style="background-image: url('<%= cl_image_path meeting.photo1.key %>'); width: 100%; height: 80px; max-height: 80px; background-size: contain; background-repeat: no-repeat; background-position: center;"></div>

      </div>

      <div style="flex: 1;" class="mt-3">
        <p class="text-center mt-2" style="max-height: 1.5em; overflow: hidden;"><%= meeting.location %></p>
        <p class="text-center italic italic_small" style="margin-top: -15px;"> Event on <%= meeting.start_time.day %> <%= t('date.abbr_month_names')[meeting.start_time.month] %> <%= meeting.start_time.year %></p>
        <% if meeting.deadline_date.present? %>
          <p class="text-center italic italic_small" style="margin-top: -15px;">Apply by <%= meeting.deadline_date.day %> <%= t('date.abbr_month_names')[meeting.deadline_date.month] %> <%= meeting.deadline_date.year %></p>
        <% end %>
      </div>
      
      <%= link_to 'View', meeting_path(meeting), class: 'btn btn-green', style: 'width: 100%' %>
    </div>
    <% end %>
  <% end %>
</div>
</div>


</body>
</html>

<style type="text/css">
  .form-control{
    width:300px;
  }
</style>


<script type="text/javascript">
  // Text to search for (case-sensitive)
  var searchText = 'Today';

  // Find all anchor elements on the page
  var allAnchors = document.getElementsByTagName('a');

  // Array to store matching anchor elements
  var matchingAnchors = [];

  // Loop through all anchor elements to find the matching ones
  for (var i = 0; i < allAnchors.length; i++) {
    var anchorElement = allAnchors[i];

    // Check if the anchor element's text matches the search text
    if (anchorElement.textContent === searchText) {
      // Add the matching anchor element to the array
      matchingAnchors.push(anchorElement);
    }
  }

  // Now matchingAnchors array contains all anchor elements with the specified text
  // You can perform actions on each matching anchor element
  matchingAnchors.forEach(function(anchorElement) {
    anchorElement.style.display = 'none'; // For example, change their color
  });

  console.log('Found matching anchor elements:', matchingAnchors);
</script>


<style type="text/css">

  .simple-calendar .calendar-heading nav {
    display: block;
  }

  .simple-calendar .calendar-heading {
    text-align: center;
    margin-top:25px;
  }

  .simple-calendar .calendar-heading nav a {
    padding: 10px 20px;
    background-color: #004080;
    color: white;
  }
</style>