config/routes.rb
Rails.application.routes.draw do
  resources :meetings do 
    resources :meetingcomments
  end
  resources :profiles, except: [:edit]
  patch '/profiles/:id', to: 'profiles#update', as: 'update_profile'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#index', as: 'root'
  resources :mailform
  resources :blogs
  get 'CV', to: 'pages#CV', as: :cv
  get 'adminpanel', to: 'pages#adminpanel', as: :adminpanel
  get 'lol', to: 'pages#lol', as: :lol
  get 'longermsg', to: 'pages#longermsg', as: :longermsg
  get 'daily', to: 'pages#daily', as: :daily
  get 'weekly', to: 'pages#weekly', as: :weekly
  get 'meetingfilter', to: 'pages#meetingfilter', as: :meetingfilter
  resources :coachingrequests
  get 'aboutus', to: 'pages#aboutus', as: :aboutus
  get 'networking', to: 'pages#networking', as: :networking
  get 'request submission', to: 'pages#requestsubmission', as: :requestsubmission
  resources :ukfinancejobs, except: [:edit] do 
    resources :comments
    member do
      post 'favorite', to: 'ukfinancejobs#favorite'
      delete 'unfavorite', to: 'ukfinancejobs#unfavorite'
    end
    collection do
      get 'favorites', to: 'ukfinancejobs#favorites'
    end
  end
  patch '/ukfinancejobs/:id', to: 'ukfinancejobs#update', as: 'update_ukfinancejob'
  get '/ukfinancejobs/:id/edit', to: 'ukfinancejobs#edit', as: 'edit_ukfinancejob'
  get 'interviews', to: 'pages#interviews', as: :interview
  get '/downloads/:filename', to: 'downloads#download', as: 'download_file'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ukfinancejob.rb
class Ukfinancejob < ApplicationRecord
	require 'pg_search'
	has_one_attached :photo
	has_many :comments, dependent: :destroy
	validates :title, :url, :company, :type_of_job, :location, :application_opening_date, :deadline_date, :eligibility, :industry, :hr_email, :app_process, :description, presence: true
 	has_many :favorites
  has_many :favorited_by_users, through: :favorites, source: :user

  include PgSearch::Model
	pg_search_scope :search_by_keyword, against: %i[title company type_of_job location description],
                                    using: {
                                      tsearch: { prefix: true }
                                    }
end

app/controllers/ukfinancejobs_controller.rb
class UkfinancejobsController < ApplicationController
  before_action :set_ukfinancejob, only: [:show, :edit, :update, :destroy]
  include ActiveModel::Dirty

  def index
    @ukfinancejobs = Ukfinancejob.order(:application_opening_date)
     # Initialize filter options
    @locations = Ukfinancejob.pluck(:location).uniq
    @types_of_job = Ukfinancejob.pluck(:type_of_job).uniq.sort
    @deadline_dates = Ukfinancejob.pluck(:deadline_date).uniq
    @companies = Ukfinancejob.pluck(:company).uniq.sort
    @fields_in_finance = Ukfinancejob.pluck(:field_in_finance).uniq.sort


    # Apply filters if provided in params
    @ukfinancejobs = @ukfinancejobs.where(location: params[:location]) if params[:location].present?
    @ukfinancejobs = @ukfinancejobs.where(company: params[:company]) if params[:company].present?
    @ukfinancejobs = @ukfinancejobs.where(type_of_job: params[:type_of_job]) if params[:type_of_job].present?
    @ukfinancejobs = @ukfinancejobs.where(deadline_date: params[:deadline_date]) if params[:deadline_date].present?
    @ukfinancejobs = @ukfinancejobs.where(rolling_admission: params[:rolling_admission]) if params[:rolling_admission].present?

    if params[:application_opening_date_filter] == 'true'
      @ukfinancejobs = @ukfinancejobs.where('application_opening_date < ?', Date.today)
    end

    @ukfinancejobs = @ukfinancejobs.where(diversity: true) if params[:diversity_filter] == 'true'

    if params[:field_in_finance].present?
      @ukfinancejobs = @ukfinancejobs.where(field_in_finance: params[:field_in_finance])
    end

    if params[:search].present?
      @ukfinancejobs = @ukfinancejobs.search_by_keyword(params[:search])
    end   
  end

  def favorite
    @ukfinancejob = Ukfinancejob.find(params[:id])
    current_user.favorite_ukfinancejobs << @ukfinancejob
    redirect_to @ukfinancejob, notice: 'UK finance job has been favorited!'
    
  end

  def unfavorite
    @ukfinancejob = Ukfinancejob.find(params[:id])
    current_user.favorite_ukfinancejobs.delete(@ukfinancejob)
    redirect_to @ukfinancejob, notice: 'UK finance job has been unfavorited.'
  end

  def favorites
    @favorite_ukfinancejobs = current_user.favorite_ukfinancejobs
  end

  def show
  end

  def new
    @ukfinancejob = Ukfinancejob.new
  end

  def create
    @ukfinancejob = Ukfinancejob.new(ukfinancejob_params)

    if @ukfinancejob.save
      redirect_to @ukfinancejob, notice: 'UK finance job was successfully created.'
    else
      render :new
    end
  end

  def edit
    @ukfinancejob = Ukfinancejob.find(params[:id])
  end

  def update
    if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date 
      @status = "OPEN"
    elsif Date.today < @ukfinancejob.application_opening_date
      @status = "NOT YET OPEN"
    else
      @status = "CLOSED"
    end

    previous_status = @status

    if @ukfinancejob.update(ukfinancejob_params)
      if previous_status != 'OPEN' && Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date 
        @favorited_jobs = Favorite.where(ukfinancejob_id: @ukfinancejob.id)
        user_ids_that_favorited_job = []
        @favorited_jobs.each do |job|
          user_ids_that_favorited_job.push(job.user_id)
        end 
        user_ids_that_favorited_job.each do |user_id|
          user = User.find(user_id)
          JobNotificationMailer.job_notification(user, @ukfinancejob).deliver_now
        end
      end
      redirect_to @ukfinancejob, notice: 'UK finance job was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ukfinancejob.destroy
    redirect_to ukfinancejobs_url, notice: 'UK finance job was successfully destroyed.'
  end

  private

  def set_ukfinancejob
    @ukfinancejob = Ukfinancejob.find(params[:id])
  end

  def ukfinancejob_params
    params.require(:ukfinancejob).permit(:application_opening_date, :eligibility, :industry, :hr_email, :app_process, :photo, :title, :url, :type_of_job, :location, :deadline_date,  :rolling_admission, :company, :guesstimate, :description, :guesstimate_deadline, :diversity, :field_in_finance, :interviewdatabool, :interviewdata, :interviewdatayear, :approved_by_admin, :numberassessment)
  end 
end

app/helpers/ukfinancejobs_helper.rb
module UkfinancejobsHelper
end

app/views/ukfinancejobs/edit.html.erb
<!-- app/views/ukfinancejobs/new.html.erb -->
<h1>Edit Job</h1>
<p> DO NOT LEAVE ANY FIELDS BLANK; copy and paste them from the career sites</p>

<%= form_with(model: @ukfinancejob, url: ukfinancejob_path(@ukfinancejob), class: 'ukfinancejob-form') do |form| %>
  <% if current_user and current_user.admin == true %>
    <div class="form-group">
      <p>Approved?</p>
      <%= form.check_box :approved_by_admin %>
    </div>
    <br>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <br>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class: 'form-control' %>
  </div>

  <br>  
  <div class="form-group">
    <%= form.label :type_of_job %>
    <%= form.select :type_of_job, options_for_select(['Summer Internship', 'Off-Cycle Internship', 'Full-time entry level', 'Insight Internship', 'Apprenticeship', 'Work Placement'], @ukfinancejob.type_of_job), {}, class: 'form-control' %>

  </div>

  <br>
  <div class="form-group">
    <%= form.label :field_in_finance %>
    <%= form.select :field_in_finance, options_for_select(['Bulge Bracket', 'Hedge Fund', 'Asset Manager', 'Private Equity', 'Elite Boutique', 'Trading/Market Makers', 'Other'], @ukfinancejob.field_in_finance), {}, class: 'form-control' %>

  </div>
  <br>
  <div class="form-group">
    <%= form.label :location %>
    <%= form.select :location, options_for_select(['London, UK', 'Worldwide',]), {}, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <p>Interview data available?</p>
    <%= form.check_box :interviewdatabool %>
  </div>
  <br>
  <div class="form-group">
    <p>Interview Data</p>
    <%= form.text_field :interviewdata, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <p>Interview Data Year</p>
    <%= form.text_field :interviewdatayear, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :application_opening_date %>
    <p class="italic_small">provide guess if not available</p>
    <%= form.date_field :application_opening_date, class: 'form-control' %>
  </div>
  <br>
   <div class="field">
    <p>Are you guessing opening date?
    <%= form.check_box :guesstimate %>
    </p>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :deadline_date %>
    <p class="italic_small">provide guess if not available</p>
    <%= form.date_field :deadline_date, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <p>Are you guessing deadline date?
    <%= form.check_box :guesstimate_deadline %>
    </p>
  </div>
  <div class="form-group">
    <%= form.label :eligibility %>
    <%= form.text_field :eligibility, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <p>Diversity event?
    <%= form.check_box :diversity %>
    </p>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :hr_email %>
    <%= form.text_field :hr_email, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :app_process %>
    <%= form.text_field :app_process, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :rolling_admission %>
    <%= form.check_box :rolling_admission %>
  </div>
  <br>

  <div class="actions text-center ">
    <%= form.submit 'UPDATE', class: ' w-100 text-center btn btn-green d-flex' %>
  </div>
<% end %>
<br>
<p>FILL ALL FIELDS. IF YOU CAN'T CLICK 'ADD' THEN ITS BECAUSE YOU LEFT A FIELD BLANK</p>

app/views/ukfinancejobs/favorites.html.erb
<!-- app/views/ukfinancejobs/favorites.html.erb -->
<h1>Your Favorite UK Finance Jobs</h1>

<% if current_user.favorite_ukfinancejobs.any? %>
  <ul>
    <% current_user.favorite_ukfinancejobs.each do |ukfinancejob| %>
      <li><%= link_to ukfinancejob.title, ukfinancejob_path(ukfinancejob) %></li>
    <% end %>
  </ul>
<% else %>
  <p>You haven't favorited any UK finance jobs yet.</p>
<% end %>

<%= link_to 'Back to All UK Finance Jobs', ukfinancejobs_path %>

app/views/ukfinancejobs/show.html.erb
<br>
<% if current_user and current_user.admin == true %>
<h4 class="text-center">
  ADMIN APPROVAL: <%= @ukfinancejob.approved_by_admin %>
</h4>
<% end %>
<br>

<button class="btn mobile-only w-100 btn-green" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample1">+ What is this?</button>

<div class="d-flex justify-content-center">
  <button class="btn desktop-only  btn-green" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample1">+ What is this?</button>  
</div>


         
<div class="collapse -only" id="collapseExample1">
  <p class="container">
    A focused and all-encompassing overview of EU/UK high finance job roles for juniors (up to associate). Make sure to take advantage of <strong>easter eggs (i.e. spring or insight internships)!</strong>
    By default, jobs are filtered chronologically by application opening date.
  </p>
</div>


<br>
<div class="desktop-only container">
    <!-- ... Rest of the code ... -->
<div class="d-flex" style="">
  <div>
    <% if user_signed_in? %>
      <div style="display: flex; justify-content: flex-start; align-items: center; width: 100%; /* Optional: Add padding or margin as needed */">
        <div style="width: 150px; margin-bottom: -180px;">
          <% if current_user.favorite_ukfinancejobs.include?(@ukfinancejob) %>
            <%= button_to unfavorite_ukfinancejob_path(@ukfinancejob), method: :delete, class: "btn large-text" do %>
              <i class="fa-solid fa-star"></i>
              <p class="small-text">
                Job Favorited
              </p>
            <% end %>
          <% else %>
            <%= button_to favorite_ukfinancejob_path(@ukfinancejob), method: :post, class: "btn large-text" do %>
              <i class="fa-regular fa-star"></i>
              <p class="small-text">
                Favorite job
              </p>
              <% if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date %>
              <% else %>
                <% if user_signed_in? %>
                  <p class="small-text">
                    <i class="fa-regular fa-bell"></i>
                    Also sets an e-mail reminder for when applications are open
                  </p>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn-dark btn border-light" %> to favorite job & set reminder
    <% end %>
    <!-- ... Rest of the code ... -->
  </div>
</div>
<!-- ... Rest of the code ... -->



      <h1 class="text-center"><%= @ukfinancejob.title %></h1>
      <h5 class="text-center">Application Status: 
        <% if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date %>
        <span style="color: #118C4F">
          OPEN
        </span>
        <% elsif Date.today < @ukfinancejob.application_opening_date %>
        <span style="color: #89CFF0;">
          NOT YET OPEN
        </span>  
        <% else %>
        <span style="color: red">
          CLOSED
        </span>
      <% end %>
      </h5>

    <div class="d-flex justify-content-center" style="margin-top: -40px;"> 
      <%= cl_image_tag @ukfinancejob.photo.key, class: "mt-5", height: 100, crop: :fill %>
    </div>
    <br>
      <div class="ukfinancejob-details">
        <p><strong>Type of Job:</strong> <%= @ukfinancejob.type_of_job %></p>
        
        <p><strong>Diversity Event:</strong> 
          <%= @ukfinancejob.diversity ? 'Yes' : 'No' %></p>    

        <p><strong>Location:</strong> <%= @ukfinancejob.location %></p>
        <p><strong>Application Opening:</strong> <%= @ukfinancejob.application_opening_date.day %> <%= t('date.abbr_month_names')[@ukfinancejob.application_opening_date.month] %> <%= @ukfinancejob.application_opening_date.year %>
          <% if @ukfinancejob.guesstimate == true %>
          <strong class="italic_small" style="color: red;">
            unconfirmed / predicted based on last years opening
          </strong>
          <% end %>

        </p>
        <p><strong>Application Deadline:</strong> <%= @ukfinancejob.deadline_date.day %> <%= t('date.abbr_month_names')[@ukfinancejob.deadline_date.month] %> <%= @ukfinancejob.deadline_date.year %>
        <% if @ukfinancejob.guesstimate_deadline == true %>
          <strong class="italic_small" style="color: red;">
            unconfirmed / predicted based on last years deadline
          </strong>
          <% end %>
          </p>
        <p><strong>Rolling Admission:</strong> 
          <%= @ukfinancejob.rolling_admission ? 'Yes' : 'No' %></p>    
        <p><strong>Eligibility:</strong> <%= @ukfinancejob.eligibility %></p>
        <!-- <p><strong>Division:</strong> <%= @ukfinancejob.industry %></p>-->
        <p><strong>HR Contact:</strong> <%= @ukfinancejob.hr_email %></p>
        <p><strong>Application Process:</strong> <%= @ukfinancejob.app_process %></p>
        <p><strong>Online Test(s) and Provider:</strong> <%= @ukfinancejob.numberassessment %></p>
        
        <% if @ukfinancejob.interviewdatabool == true %>
        <% @interviewdata = @ukfinancejob.interviewdata.split(';') %>
          <p><strong>Interview Process & questions:*</strong> 
            <ol>
            <% @interviewdata.each do |i| %>
              <li style="font-size:16px;">
                <%= i %>
              </li>
              
            <% end %>
            </ol>
            <p class="small-text">*data from <%= @ukfinancejob.interviewdatayear %></p>
           
          </p>
        <% else %>
        <p>
          <strong>Interview Process & questions:</strong>
        <span class="italic_small">
          We will add details here as they becomes available
        </span></p>
        <% end %>

        <p><strong>Description:</strong> <%= @ukfinancejob.description %></p>
        <a class="card-text btn btn-green w-100 mb-3" href="<%= @ukfinancejob.url%>" target="_blank"><strong>
          Link to career website</strong></a>
          <% if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date %>
          <% else %>   
          <strong>Given applications are not yet open, you may not find the job posting on the career site just yet.
          </strong>      
        <% end %>
      </div>  
    </div>
    
    
  </div>
</div>


<% if current_user and current_user.admin == true %>

<div class="d-flex justify-content-around"> 
<%= link_to 'Edit', edit_ukfinancejob_path(@ukfinancejob), class: 'btn btn-primary' %>

<%= button_to 'Delete', ukfinancejob_path(@ukfinancejob), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this job?' }, form: { "data-remote": true } %>

</div>
<% end %>
<br>
<br>


<div class="mobile-only">
  <div>

    <div>
      <div style="margin-top: -50px;">
     <% if user_signed_in? %>
     <div class="d-flex justify-content-center">
       <% if current_user.favorite_ukfinancejobs.include?(@ukfinancejob) %>
            <%= button_to unfavorite_ukfinancejob_path(@ukfinancejob), method: :delete, class: "btn large-text" do %>
              <div style="display: block; margin: auto;">
                <i class="fa-solid fa-star"></i>
                <p class="small-text">
                Job Favorited
                </p>
                <% end %>
              </div>  
          <% else %>
     </div>
            

            <div style="display: block; margin: auto;" >
            <%= button_to  favorite_ukfinancejob_path(@ukfinancejob), method: :post, class: "btn large-text" do %>

              <i class="fa-regular fa-star"></i>
              <p class="small-text">
                Favorite job
              </p>
               <% if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date %>
                <% else %>
                  <% if user_signed_in? %>
                    <p class="small-text">
                      <i class="fa-regular fa-bell"></i>
                      Also sets an e-mail reminder for when applications are open
                    </p>
                <% end %>  

            <% end %>

            <% end %>

            <% end %>
            <% else %>
            <%= link_to new_user_session_path, class: "btn border-light" do %>
              <i class="fa-regular fa-star large-text"></i> <p class="small">Favorite job</p>

<% end %>

<br>
<br>
      <% end %>
<div class="d-flex justify-content-center mt-3" style="background-image: url('<%= cl_image_path @ukfinancejob.photo.key %>'); width: 45%; display: block; margin: auto; height: 80px; max-height: 80px; background-size: contain; background-repeat: no-repeat; background-position: center;"></div>
      <div class="ukfinancejob-details">
        <br>

      <h5 class="text-center w-100"><%= @ukfinancejob.title %></h5>
      <h6 class="text-center">Application Status: 
      <% if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date %>
      <span style="color: #118C4F">
        OPEN
      </span>  
      </h6>
      <% elsif Date.today < @ukfinancejob.application_opening_date %>
        <span style="color: #89CFF0;">
          NOT YET OPEN
        </span>  
      <% else %>
      <span style="color: red">
        CLOSED
      </span>
      <% end %>
      </h5>
      
      
        <br>
        <p><strong>Type:</strong> <%= @ukfinancejob.type_of_job %></p>
        <p><strong>Location:</strong> <%= @ukfinancejob.location %></p>
        <p><strong>Application Opening:</strong> <%= @ukfinancejob.application_opening_date.day %> <%= t('date.abbr_month_names')[@ukfinancejob.application_opening_date.month] %> <%= @ukfinancejob.application_opening_date.year %>
        <% if @ukfinancejob.guesstimate == true %>
          <strong class="italic_small" style="color: red;">
            unconfirmed / predicted based on last years opening
          </strong>
          <% end %>
        </p>
        <p><strong>Application Deadline:</strong> <%= @ukfinancejob.deadline_date.day %> <%= t('date.abbr_month_names')[@ukfinancejob.deadline_date.month] %> <%= @ukfinancejob.deadline_date.year %>
        <% if @ukfinancejob.guesstimate_deadline == true %>
          <strong class="italic_small" style="color: red;">
            unconfirmed / predicted based on last years deadline
          </strong>
          <% end %></p>
        <p><strong>Rolling Admission:</strong> <%= @ukfinancejob.rolling_admission ? 'Yes' : 'No' %></p>
        <p><strong>Eligibility:</strong> <%= @ukfinancejob.eligibility %></p>
        <!-- <p><strong>Division:</strong> <%= @ukfinancejob.industry %></p>-->
        <p><strong>HR Contact:</strong> <%= @ukfinancejob.hr_email %></p>
        <p><strong>Application Process:</strong> <%= @ukfinancejob.app_process %></p>
        <% if @ukfinancejob.interviewdatabool == true %>
          <p><strong>Interview Process & questions:</strong> 
            <ol>
            <% @interviewdata.each do |i| %>
              <li style="font-size:16px;">
                  <%= i %>  
              </li>
              
            <% end %>
            </ol>
           
          </p>
        <% else %>
        <p class="italic_small">
          We will add details here as it becomes available
        </p>
        <% end %>
        <p><strong>Description:</strong> <%= @ukfinancejob.description %></p>
          <br>
          <br>
          <a class="card-text btn btn-green w-100 mb-3" href="<%= @ukfinancejob.url%>" target="_blank"><strong>
          Link to career website</strong></a>
          <% if Date.today >= @ukfinancejob.application_opening_date && Date.today <= @ukfinancejob.deadline_date %>
          <% else %>   
          <strong>Given applications are not yet open, you may not find the job posting on the career site just yet.
          </strong>      
        <% end %>
      </div>  
    </div>
  </div>
  
</div>


</div>


<!-- job comments -->

<div class="container m-">
  
<h4 class="text-center">Comments</h4>

<% @ukfinancejob.comments.each do |comment| %>
  <div class=" m-3 p-2 round-border">
    <p>
      <%= comment.content %>  
    </p>
    <p>
      <i class="fa-sharp fa-regular fa-user"></i> <%= link_to comment.user.email.split("@").first, profile_path(comment.user), class: "no-style" %>
      <span style="font-size:12px;">
        on <%= comment.created_at.strftime("%e %B %Y") %>  
      </span>
    </p>
  </div>
  <hr>
<% end %>

<% if current_user.present? %>
    <%= form_with(model: [@ukfinancejob, Comment.new], url: ukfinancejob_comments_path(@ukfinancejob)) do |form| %>
    <div> 
      <%= form.text_area :content, placeholder: 'Enter your comment', class: "d-flex w-100 p-2" %>
    </div>
    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
    <br>
    <%= form.submit 'Add Comment', class: "btn btn-green w-100" %>
  <% end %>
<% else %>
<p>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-dark' %>
  to comment
</p>
<% end %>

</div>





<style type="text/css">
  
.large-text{
  font-size:30px;
}
.small-text{
  font-size:12px;
}
</style>